import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const root = path.resolve(import.meta.dirname, "../..");
const cli = path.join(root, "tools/devflow/devflow.ts");
const stateFile = path.join(root, ".grado/devflow/state.json");
const stageFile = path.join(root, ".grado/devflow/stage.yaml");
const initialState = fs.readFileSync(stateFile, "utf8");
const initialStage = fs.readFileSync(stageFile, "utf8");
const run = (args: string[], input = "") => execFileSync(process.execPath, [cli, ...args], { cwd: root, input, encoding: "utf8" });
const runWithoutExecutors = (args: string[], input = "") => { const env = { ...process.env }; delete env.RELAY_URL; delete env.ANTHROPIC_API_KEY; delete env.OPENAI_API_KEY; return execFileSync(process.execPath, [cli, ...args], { cwd: root, input, encoding: "utf8", env }); };
const reset = () => { fs.writeFileSync(stateFile, initialState); fs.writeFileSync(stageFile, initialStage); };
const result = (id: string, wp: string, proof: string, extra: Record<string, unknown> = {}) => JSON.stringify({ schema_version: 1, result_id: id, work_package_id: wp, claim: { status: "COMPLETE" }, validation_facts: [{ type: "proof-validation", proof_id: proof, passed: true, evidence_refs: [`git:${id}`] }], ...extra });
const status = () => JSON.parse(run(["status", "--json"]));
const reconcile = (body: string) => JSON.parse(run(["reconcile"], body));
const configureReview = (change: (stage: Record<string, unknown>) => void) => { const stage = JSON.parse(initialStage) as Record<string, unknown>; change(stage); fs.writeFileSync(stageFile, JSON.stringify(stage)); };
test.after(reset);

test("initial state is NOT_DUE and engine is implemented", () => { reset(); const out = status(); assert.equal(out.review_status, "NOT_DUE"); assert.equal(out.exit_gate.complete, false); });
test("key proof transition triggers DUE", () => { reset(); const out = reconcile(result("key", "WP-PVX-S1-P1", "PVX-S1-P1")); assert.equal(out.review_status, "DUE"); assert.ok(out.review_reasons.includes("KEY_PROOF_OBLIGATION_SATISFIED:PVX-S1-P1")); assert.equal(out.next_eligible_action, "ALIGNMENT_REVIEW"); });
test("non-key proof does not trigger key-proof rule", () => { reset(); const out = reconcile(result("non-key", "WP-PVX-S1-P2", "PVX-S1-P2")); assert.equal(out.review_status, "NOT_DUE"); assert.equal(out.review_reasons.some((x: string) => x.startsWith("KEY_PROOF_OBLIGATION_SATISFIED")), false); });
test("work cluster completion triggers DUE", () => { reset(); configureReview((s) => { const p = s.review_policy as Record<string, unknown>; p.key_proof_obligations = []; p.max_review_gap = 99; }); for (let i = 1; i <= 5; i += 1) reconcile(result(`cluster-${i}`, `WP-PVX-S1-P${i}`, `PVX-S1-P${i}`)); const out = status(); assert.equal(out.review_status, "DUE"); assert.ok(out.review_reasons.includes("WORK_CLUSTER_COMPLETE:PVX-S1-CLUSTER")); });
test("CREATE top-level abstraction is BLOCKING", () => { reset(); const out = reconcile(result("create", "WP-PVX-S1-P1", "PVX-S1-P1", { architecture_fit: { change: "CREATE", proposed_top_level_abstraction: "NewBoundary" } })); assert.equal(out.review_status, "BLOCKING"); assert.equal(out.next_eligible_action, "TOP_LEVEL_DECISION"); });
test("max review gap triggers DUE", () => { reset(); configureReview((s) => { const p = s.review_policy as Record<string, unknown>; p.key_proof_obligations = []; p.max_review_gap = 1; }); const out = reconcile(result("gap", "WP-PVX-S1-P2", "PVX-S1-P2")); assert.equal(out.review_status, "DUE"); assert.ok(out.review_reasons.includes("MAX_REVIEW_GAP")); });
test("exit gate triggers mandatory pre-exit review", () => { reset(); configureReview((s) => { const p = s.review_policy as Record<string, unknown>; p.key_proof_obligations = []; p.max_review_gap = 99; }); for (let i = 1; i <= 5; i += 1) reconcile(result(`exit-${i}`, `WP-PVX-S1-P${i}`, `PVX-S1-P${i}`)); const out = status(); assert.equal(out.exit_gate.complete, true); assert.equal(out.review_status, "DUE"); assert.ok(out.review_reasons.includes("MANDATORY_PRE_EXIT")); assert.equal(out.next_eligible_action, "ALIGNMENT_REVIEW"); });
test("DUE and duplicate results remain blocked and idempotent", () => { reset(); const body = result("duplicate", "WP-PVX-S1-P1", "PVX-S1-P1"); const first = reconcile(body); const second = reconcile(body); assert.equal(first.review_status, "DUE"); assert.equal(second.next_eligible_action, "ALIGNMENT_REVIEW"); const state = JSON.parse(fs.readFileSync(stateFile, "utf8")); assert.equal(state.results.length, 1); });
test("review trigger state survives restart", () => { reset(); reconcile(result("restart", "WP-PVX-S1-P1", "PVX-S1-P1")); const reloaded = status(); assert.equal(reloaded.review_status, "DUE"); assert.equal(reloaded.work_completed_since_last_review, 1); });
test("DUE remains blocked for ordinary work", () => { reset(); reconcile(result("due-block", "WP-PVX-S1-P1", "PVX-S1-P1")); const out = reconcile(result("after-due", "WP-PVX-S1-P2", "PVX-S1-P2")); assert.equal(out.review_status, "DUE"); assert.equal(out.next_eligible_action, "ALIGNMENT_REVIEW"); });
test("controller runs without Relay or provider credentials", () => { reset(); const out = JSON.parse(runWithoutExecutors(["status", "--json"])); assert.equal(out.review_status, "NOT_DUE"); });
test("invalid StageSpec and unknown WorkPackage remain rejected", () => { reset(); fs.writeFileSync(stageFile, JSON.stringify({ schema_version: 1, stage: { id: "BAD" }})); assert.throws(() => status()); reset(); assert.throws(() => reconcile(JSON.stringify({ schema_version: 1, result_id: "unknown", work_package_id: "WP-UNKNOWN", claim: { status: "COMPLETE" }}))); });
